### ISSUE TITLE
Summary Statistics tool is missing

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#52]
Statistics > 'Summary Statistics for any numerical column' tool is missing in GVL-4.1.0. 
The tool: /mnt/galaxy/galaxy-app/tools/stats/gsummary.py

The tool does not work on GVL-4.0.0. The error message says: No module named rpy

**Comment by madisonkeene** [comment]
Removed completely - doesn't work because of rpy issues

**Comment by afgane** [comment]
This has been fixed in the ansible-galaxy-cloudman-setup role: https://github.com/galaxyproject/ansible-cloudman-galaxy-setup/pull/7

**Comment by AndrewIsaac** [comment]
UPDATE: Need to verify if this is still broken in Galaxy-main because it is not in our control

**Comment by jessicachung** [comment]
Summary Statistics works in Galaxy-main, but is still broken in our current 4.2 dev.

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/tools/stats/gsummary.py", line 124, in <module>
    main()
  File "/mnt/galaxy/galaxy-app/tools/stats/gsummary.py", line 65, in main
    tmp_file.write( "%s\n" % hdr_str )
  File "/mnt/galaxy/tools/_conda/envs/__rpy2@2.7.8/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Slugger70** [comment]
I use the fact that it is reliably broken in my training workshops.. However, fixing it would be better.. It is one of the tools that comes with Galaxy. We should ask galaxyproject how they fixed it.
