### ISSUE TITLE
Galaxy Reports issues

### ISSUE THREAD

**Issue by igormakunin** [gvlproject/gvl_image_playbook#65]
There are issues with Reports, eg it shows only 50 jobs per user, does not show jobs for previous months, etc. Derek updated a test Galaxy via github, but the update did not fix Reports.

**Comment by Slugger70** [comment]
Apparently this is fixed in Galaxy 16.07. It was a Galaxy bug and I got it to work for the 16.07 test install I did.

**Comment by igormakunin** [comment]
Derek has upgraded a test GVL Galaxy to 16.07, but the upgrade did not fix Reports.

**Comment by AndrewIsaac** [comment]
This should be reported in Galaxy-main github

**Comment by Slugger70** [comment]
Fixed in galaxy 17.01
